name: Deploy to Google Cloud Run

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - id: "auth"
        uses: "google-github-actions/auth@v2"
        with:
          credentials_json: "${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}"

      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v2"

      - name: Build and push Docker image
        run: |
          gcloud builds submit --tag gcr.io/raven-docs-437316/flask-app

      - name: Deploy to Google Cloud Run
        run: |
          gcloud run deploy flask-app \
            --image gcr.io/raven-docs-437316/flask-app \
            --platform managed \
            --region us-central1 \
            --allow-unauthenticated \
            --set-env-vars SECRET_KEY=${{ secrets.SECRET_KEY }},JWT_SECRET_KEY=${{ secrets.JWT_SECRET_KEY }},GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }},GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }},GOOGLE_PROJECT_ID=${{ secrets.GOOGLE_PROJECT_ID }},GOOGLE_AUTH_URI=${{ secrets.GOOGLE_AUTH_URI }},GOOGLE_TOKEN_URI=${{ secrets.GOOGLE_TOKEN_URI }},GOOGLE_AUTH_PROVIDER_X509_CERT_URL=${{ secrets.GOOGLE_AUTH_PROVIDER_X509_CERT_URL }},GOOGLE_REDIRECT_URI_1=${{ secrets.GOOGLE_REDIRECT_URI_1 }},GOOGLE_USER_INFO_ENDPOINT=${{ secrets.GOOGLE_USER_INFO_ENDPOINT }}
